export const CHANGE_VALUE_SELECT = 'FILTER_SELECT/CHANGE_VALUE_SELECT';

export const CHANGE_VALUE_SORT_BY = 'FILTER_SELECT/CHANGE_VALUE_SORT_BY';

export const CHANGE_VALUE_INPUT = 'FILTER_SELECT/CHANGE_VALUE_INPUT';

export const MOVIE_COUNT = 'FILTER_SELECT/SELECT_MOVIE_COUNT';