export const START_GET_MOVIE_DETAILS_REQUEST = 'SAGAS_WATCH/START_GET_MOVIE_DETAILS_REQUEST';

export const GET_MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_ID/GET_MOVIE_DETAILS_REQUESTGET_REQUEST';

export const REMEMBER_ID_MOVIE = 'MOVIE_DETAILS_ID/REMEMBER_ID_MOVIE';