export const START_HOME_GET_REQUEST = 'SAGAS_WATCH/START_HOME_GET_REQUEST';

export const GET_REQUEST = 'GET_DATA_HOME_TABLE/GET_REQUEST';

export const COUNTER_PAGE_ACTIVE = 'CHANGE_PAGE_ACTIVE_HOME_TABLE/COUNTER_PAGE_ACTIVE';

export const SAVE_SCROLL_HEIGHT = 'SAVE_SCROLL_HEIGHT_HOME_TABLE/SAVE_SCROLL_HEIGHT';

export const COUNTER_DOWNLOADED_MOVIES = 'COUNTER_DOWNLOADED_MOVIES_HOME_TABLE/SAVE_SCROLL_HEIGHT';

